services:
  nukevideo-api:
    image: nukevideo
    build:
      context: .
    volumes:
      - ./:/var/www/html

  nukevideo-queue:
    image: nukevideo
    command: "php artisan horizon -n"
    restart: unless-stopped
    volumes:
      - ".:/var/www/html"

  nukevideo-worker:
    image: nukevideo-worker
    build:
      context: .
    command: ["php", "/var/www/html/artisan", "queue:work", "--queue=streams", "--timeout=3200"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "healthcheck-queue"]
      start_period: 10s
    volumes:
      - ./:/var/www/html
      - shared-storage:/var/www/html/storage/shared
  nukevideo-cdn:
    image: nukevideo-cdn
    build:
      context: ./vod
    env_file:
      - ./vod/.env
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  rustfs:
    image: rustfs/rustfs:latest
    restart: unless-stopped
    volumes:
      - rustfs-data:/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  shared-storage:
    driver: local
  mariadb-data:
    driver: local
  rustfs-data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    external: true
    name: local
